---
- hosts: all
  vars:
    required_mounts:
      - /prom/data
      - /prom/logs

  tasks:
    - name: debug mountpoint
      set_fact:
        mount_points: "{{ ansible_mounts|json_query('[].mount') }}"

    - name: check fs
      debug:
        var: mount_points 


PLAY [all] ******************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhohst]

TASK [debug mountpoint] *****************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [check fs] *************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "mount_points": [
        "/prom/logs",
        "/prom",
        "/var/opt/CARKaim",
        "/boot",
        "/",
        "/opt",
        "/var/audit",
        "/var",
        "/prom/data",
        "/graf/logs",
        "/usr/openv",
        "/tmp",
        "/usr/home",
        "/graf",
        "/appl",
        "/local",
        "/var/tmp",
        "/opt/esm"
    ]
